import { Router } from 'express';
import { GeneratePortfolio } from '../controller/portfolioController.js';
import multer from 'multer';
import { upload } from '../db/cloudinary.js';
import { handleUpload } from '../controller/uploadController.js';
const router = Router();
const memoryUpload = multer({ storage: multer.memoryStorage() });
router.post('/upload', upload.single('image'), handleUpload);
router.post('/generate', memoryUpload.single('resume'), GeneratePortfolio);
export default router;
